name: ToiGamo Win7 | Tailscale

on:
  workflow_dispatch:
          

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Cài Tailscale 
       run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        sudo tailscale up
        sudo apt-get update
        sudo apt-get install ufw
        sudo ufw allow 3388/tcp
        sudo ufw enable
        sudo ufw status
     - name: Cài Win7 Và Chạy
       run: |
        sudo chmod 666 /dev/kvm
        echo "Đang Tải Xuống"
        wget -O w7x64.img https://bit.ly/akuhnetw7X64
        sudo apt-get install qemu &>/dev/null &
        sudo qemu-system-x86_64 -hda w7x64.img -m 8G -smp cores=4 -net user,hostfwd=tcp::3388-:3389 -net nic -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 -vga vmware -nographic &>/dev/kvm &
        sleep 43200 &>/dev/null &
        tailscale ip -4
